---
title: "Data cleaning with {purrr}"
description: |
  A tutorial on using {purrr} for data cleaning.
author:
  - name: Lea Frank
date: 05-13-2021
output:
  distill::distill_article:
    toc: true
    toc_float: true
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(fs)
```

## Batch Loading

```{r}
rootpath <- here::here("data")
```

```{r}
dir_ls(rootpath,
       regexp = "DEMO")
```

### Demographics data

```{r, include=TRUE}

demos <- dir_ls(rootpath, 
                 regexp = "DEMO") %>% 
  map_dfr(rio::import, .id = "file") %>% 
  mutate(year = str_extract(file, "\\d{4}-\\d{4}")) %>% 
  select(year, SEQN, RIDAGEYR, RIAGENDR, 
         RIDRETH1, DMDEDUC2, DMDEDUC3)
names(demos) <- c("year", "id","age","gender",
                  "race_ethnic","educ_adult","educ_child") 

fsq <- dir_ls(rootpath, 
                 regexp = "FSQ") %>% 
  map_dfr(rio::import, .id = "file") %>% 
  mutate(year = str_extract(file, "\\d{4}-\\d{4}"),
         hh_food_secure = ifelse(year == "1999-2000" | year == "2001-2002", 
                                 HHFDSEC, FSDHH)) %>% 
  select(year, SEQN, hh_food_secure)
names(fsq)[2] <- "id"
  
```

```{r}
df <- left_join(demos, fsq)
head(df)
```

```{r}
write_csv(df, str_c(rootpath,"/nhanes_1999-2016.csv"))

```

