---
title: "convert_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
years <- list.files() %>% 
  str_subset(pattern = "convert_data.Rmd", negate = TRUE) %>% 
  str_subset(pattern = "2013_2014", negate = TRUE)

idxNames <- tibble(orig = c("DEMO","DBQ","HSQ","PAQ","CFQ"),
                   new = c("demographic","diet_behavior","current_health","physical_activity","cognitive_function"))

for (i in years[2:4]) {
  fnames <- list.files(i)
  
  dfs <- map(fnames, ~{
    pathname <- str_c(i, .x, sep = "/")
    df <- haven::read_xpt(pathname)
    
    fhead <- str_split(.x, pattern = "_")[[1]][1]
    pathname <- str_c(i,"/",idxNames$new[idxNames$orig==fhead],".csv")
    write_csv(df, pathname)
    
    return(df)
  })
  
  fnames <- str_split(fnames, pattern = "_") %>% 
    map(1) %>% 
    unlist()
  
  names(dfs) <- fnames
  
  qs <- dfs[names(dfs) != "DEMO"]
  
  df <- qs[[1]]
  for (q in seq(2,length(qs))){
    df <- left_join(df, qs[[q]])
  }
  
  pathname <- str_c(i,"/questionnaire.csv")
  write_csv(df,pathname)
}

# manually writing the cognitive function data file into the questionnaires data file for 2013-2014
cog <- haven::read_xpt("2013_2014/CFQ_H.XPT")
questionnaire <- rio::import("2013_2014/questionnaire.csv")
questionnaire <- left_join(questionnaire, cog)
write_csv(questionnaire, "2013_2014/questionnaire.csv")
```


